name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag markolan/beer-viewer:latest --tag markolan/beer-viewer:$(date +%s) .
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image
      run: docker push markolan/beer-viewer:latest
